âœ“ WandB initialized in Online mode
Files already downloaded and verified
Files already downloaded and verified
This is a test to see the loss values when the network is not trained at all
Zp Model Recon Loss for epoch0 1.4867035147479124
My Preditive Coding Model with Dense layers
Accuracy:9.821636363636363 and Recon Loss:0.37165181441685124
Zp Model Recon Loss for epoch1 1.4865520012653088
My Preditive Coding Model with Dense layers
Accuracy:9.821636363636363 and Recon Loss:0.3716509586862286
Zp Model Recon Loss for epoch2 1.4866261412115658
My Preditive Coding Model with Dense layers
Accuracy:9.821636363636363 and Recon Loss:0.3716458361929335
Zp Model Recon Loss for epoch3 1.4865587047298852
My Preditive Coding Model with Dense layers
Accuracy:9.821636363636363 and Recon Loss:0.3716611639617959
Zp Model Recon Loss for epoch4 1.4866293915702253
My Preditive Coding Model with Dense layers
Accuracy:9.821636363636363 and Recon Loss:0.3716718780872462
Zp Model Recon Loss for epoch5 1.486508142307896
My Preditive Coding Model with Dense layers
Accuracy:9.821636363636363 and Recon Loss:0.3716407202546249
Zp Model Recon Loss for epoch6 1.4866504900900603
My Preditive Coding Model with Dense layers
Accuracy:9.821636363636363 and Recon Loss:0.37166124132588085
Zp Model Recon Loss for epoch7 1.4866460363578309
My Preditive Coding Model with Dense layers
Accuracy:9.821636363636363 and Recon Loss:0.37169519127787226
Zp Model Recon Loss for epoch8 1.486577712056582
My Preditive Coding Model with Dense layers
Accuracy:9.821636363636363 and Recon Loss:0.37164243545068804
Traceback (most recent call last):
  File "/home/ajinkya/projects/TestRepo_MsThesis_Ajinkya/week6/main.py", line 192, in <module>
    main()
  File "/home/ajinkya/projects/TestRepo_MsThesis_Ajinkya/week6/main.py", line 151, in main
    train_bool = reconstruction_testing_on_random_network(net,save_dir, trainloader, testloader,config)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ajinkya/projects/TestRepo_MsThesis_Ajinkya/week6/main.py", line 113, in reconstruction_testing_on_random_network
    zp_test_loss=recon_pc_loss(net,trainloader,config)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ajinkya/projects/TestRepo_MsThesis_Ajinkya/week6/eval_and_plotting.py", line 67, in recon_pc_loss
    for batch_idx,batch in enumerate(dataloader):
                           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ajinkya/miniconda3/envs/cuda_pyt/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 701, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/home/ajinkya/miniconda3/envs/cuda_pyt/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 757, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ajinkya/miniconda3/envs/cuda_pyt/lib/python3.12/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "/home/ajinkya/miniconda3/envs/cuda_pyt/lib/python3.12/site-packages/torchvision/datasets/cifar.py", line 119, in __getitem__
    img = self.transform(img)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/ajinkya/miniconda3/envs/cuda_pyt/lib/python3.12/site-packages/torchvision/transforms/transforms.py", line 95, in __call__
    img = t(img)
          ^^^^^^
  File "/home/ajinkya/miniconda3/envs/cuda_pyt/lib/python3.12/site-packages/torchvision/transforms/transforms.py", line 137, in __call__
    return F.to_tensor(pic)
           ^^^^^^^^^^^^^^^^
  File "/home/ajinkya/miniconda3/envs/cuda_pyt/lib/python3.12/site-packages/torchvision/transforms/functional.py", line 174, in to_tensor
    img = img.permute((2, 0, 1)).contiguous()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
Exception ignored in atexit callback: <function _start_and_connect_service.<locals>.teardown_atexit at 0x7febfe66f2e0>
Traceback (most recent call last):
  File "/home/ajinkya/miniconda3/envs/cuda_pyt/lib/python3.12/site-packages/wandb/sdk/lib/service/service_connection.py", line 54, in teardown_atexit
    conn.teardown(hooks.exit_code)
  File "/home/ajinkya/miniconda3/envs/cuda_pyt/lib/python3.12/site-packages/wandb/sdk/lib/service/service_connection.py", line 182, in teardown
    self._router.join()
  File "/home/ajinkya/miniconda3/envs/cuda_pyt/lib/python3.12/site-packages/wandb/sdk/interface/router.py", line 75, in join
    self._thread.join()
  File "/home/ajinkya/miniconda3/envs/cuda_pyt/lib/python3.12/threading.py", line 1149, in join
    self._wait_for_tstate_lock()
  File "/home/ajinkya/miniconda3/envs/cuda_pyt/lib/python3.12/threading.py", line 1169, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt:
