{"time":"2025-06-16T19:04:44.66505295+02:00","level":"INFO","msg":"stream: starting","core version":"0.20.1","symlink path":"/home/ajinkya/projects/TestRepo_MsThesis_Ajinkya/week3/wandb/run-20250616_190444-hizcc8gb/logs/debug-core.log"}
{"time":"2025-06-16T19:04:44.78355537+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:36231->[::1]:53: read: connection refused"}
{"time":"2025-06-16T19:04:47.087978519+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:39451->[::1]:53: read: connection refused"}
{"time":"2025-06-16T19:04:51.519462335+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:44622->[::1]:53: read: connection refused"}
{"time":"2025-06-16T19:05:01.144844403+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:41836->[::1]:53: read: connection refused"}
{"time":"2025-06-16T19:05:19.352415884+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:56316->[::1]:53: read: connection refused"}
{"time":"2025-06-16T19:05:54.723961622+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:60411->[::1]:53: read: connection refused"}
{"time":"2025-06-16T19:06:54.725461735+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:39835->[::1]:53: read: connection refused"}
{"time":"2025-06-16T19:07:54.726309962+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:52530->[::1]:53: read: connection refused"}
{"time":"2025-06-16T19:08:54.72753363+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:56291->[::1]:53: read: connection refused"}
{"time":"2025-06-16T19:09:54.728311935+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:59314->[::1]:53: read: connection refused"}
{"time":"2025-06-16T19:10:54.729839308+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:56851->[::1]:53: read: connection refused"}
{"time":"2025-06-16T19:11:54.730899638+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:35256->[::1]:53: read: connection refused"}
{"time":"2025-06-16T19:12:54.731638016+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:34466->[::1]:53: read: connection refused"}
{"time":"2025-06-16T19:13:54.732495866+02:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai on [::1]:53: read udp [::1]:34022->[::1]:53: read: connection refused"}
