âœ“ WandB initialized in Online mode
Files already downloaded and verified
Files already downloaded and verified
The Iteration0:
================================
Epoch:0 and AverageLoss:0.23337014804563255
Test Loss 0.12998029070941708
Epoch:1 and AverageLoss:0.11166635527254065
Test Loss 0.09780891333954243
Epoch:2 and AverageLoss:0.08960658868255518
Test Loss 0.08226297211043443
Epoch:3 and AverageLoss:0.07724765663409172
Test Loss 0.07234148096434678
Epoch:4 and AverageLoss:0.06885441964315941
Test Loss 0.0652692550911179
Epoch:5 and AverageLoss:0.06271880070495484
Test Loss 0.05996811206016359
Epoch:6 and AverageLoss:0.058062230267793016
Test Loss 0.05593931972037388
Epoch:7 and AverageLoss:0.05442347018348286
Test Loss 0.05265991201129141
Epoch:8 and AverageLoss:0.05143871921521928
Test Loss 0.04994243930412244
Epoch:9 and AverageLoss:0.04893585622234418
Test Loss 0.04760916417912592
Epoch:10 and AverageLoss:0.046734056633223046
Test Loss 0.04557207811482345
Epoch:11 and AverageLoss:0.04479434497444831
Test Loss 0.0437582143216948
Epoch:12 and AverageLoss:0.043068265852034854
Test Loss 0.0421269604393953
Epoch:13 and AverageLoss:0.041507172052893795
Test Loss 0.04074774078930481
Epoch:14 and AverageLoss:0.0401199334074774
Test Loss 0.039387506208842314
Epoch:15 and AverageLoss:0.03884024767543349
Test Loss 0.03813480807444717
Epoch:16 and AverageLoss:0.037685681591787
Test Loss 0.03704232024618342
Epoch:17 and AverageLoss:0.03664580428653666
Test Loss 0.03610727054220211
Epoch:18 and AverageLoss:0.03568348272339157
Test Loss 0.03513960898677005
Epoch:19 and AverageLoss:0.03480924577321238
Test Loss 0.03429731351759615
Model Save Sucessfully
Training Sucessful
The Iteration1:
================================
Traceback (most recent call last):
  File "/home/ajinkya/projects/TestRepo_MsThesis_Ajinkya/week5/main.py", line 304, in <module>
    main()
  File "/home/ajinkya/projects/TestRepo_MsThesis_Ajinkya/week5/main.py", line 220, in main
    torch.load(
  File "/home/ajinkya/miniconda3/envs/cuda_pyt/lib/python3.12/site-packages/torch/serialization.py", line 1319, in load
    with _open_file_like(f, "rb") as opened_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ajinkya/miniconda3/envs/cuda_pyt/lib/python3.12/site-packages/torch/serialization.py", line 659, in _open_file_like
    return _open_file(name_or_buffer, mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ajinkya/miniconda3/envs/cuda_pyt/lib/python3.12/site-packages/torch/serialization.py", line 640, in __init__
    super().__init__(open(name, mode))
                     ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/models/reconstruction_pc_pretrain/reconstruction_pc_pretrain_1.pth'
