âœ“ WandB initialized in Online mode
Files already downloaded and verified
Files already downloaded and verified
The Iteration0:
================================
Epoch:0 and AverageLoss:0.3012413315176964
Test Loss 0.12632944810390473
Epoch:1 and AverageLoss:0.09328346745371818
Test Loss 0.06919315056502819
Epoch:2 and AverageLoss:0.05338869082033634
Test Loss 0.04081918571889401
Epoch:3 and AverageLoss:0.03336048116981983
Test Loss 0.027155135229229927
Epoch:4 and AverageLoss:0.022969620874524116
Test Loss 0.01929519372060895
Epoch:5 and AverageLoss:0.016575181686133145
Test Loss 0.014095500349998473
Epoch:6 and AverageLoss:0.012252477516233921
Test Loss 0.010556091230362654
Epoch:7 and AverageLoss:0.009298918392881751
Test Loss 0.008127560766413808
Epoch:8 and AverageLoss:0.007251712499558926
Test Loss 0.006425678472965956
Epoch:9 and AverageLoss:0.005793643124029041
Test Loss 0.005191254572942853
Model Save Sucessfully
Training Sucessful
The Iteration1:
================================
Epoch:0 and AverageLoss:0.004669698121771216
Test Loss 0.004134493484161794
Epoch:1 and AverageLoss:0.003746437647379935
Test Loss 0.00337880193348974
Epoch:2 and AverageLoss:0.0031093051210045815
Test Loss 0.002846092816442251
Epoch:3 and AverageLoss:0.0026514483782462774
Test Loss 0.00245518412720412
Epoch:4 and AverageLoss:0.0023149920033290984
Test Loss 0.0021653721854090692
Epoch:5 and AverageLoss:0.0020565251052379607
Test Loss 0.0019378308821469546
Epoch:6 and AverageLoss:0.001852063074707985
Test Loss 0.0017609694031998516
Epoch:7 and AverageLoss:0.0016864513480104506
Test Loss 0.00161023640492931
Epoch:8 and AverageLoss:0.0015495573794469238
Test Loss 0.00148114879662171
Epoch:9 and AverageLoss:0.0014332124471664429
Test Loss 0.0013738426533527672
Model Save Sucessfully
Training Sucessful
Traceback (most recent call last):
  File "/home/ajinkya/projects/TestRepo_MsThesis_Ajinkya/week8/main.py", line 298, in <module>
    main()
  File "/home/ajinkya/projects/TestRepo_MsThesis_Ajinkya/week8/main.py", line 272, in main
    accuracy_dict = testing_model(net,trainloader,testloader,config,20)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ajinkya/projects/TestRepo_MsThesis_Ajinkya/week8/main.py", line 219, in testing_model
    net.load_state_dict(
  File "/home/ajinkya/miniconda3/envs/cuda_pyt/lib/python3.12/site-packages/torch/nn/modules/module.py", line 2584, in load_state_dict
    raise RuntimeError(
RuntimeError: Error(s) in loading state_dict for Net:
	size mismatch for fc3.weight: copying a param with shape torch.Size([10, 84]) from checkpoint, the shape in current model is torch.Size([2, 84]).
	size mismatch for fc3.bias: copying a param with shape torch.Size([10]) from checkpoint, the shape in current model is torch.Size([2]).
	size mismatch for fc3_fb.weight: copying a param with shape torch.Size([84, 10]) from checkpoint, the shape in current model is torch.Size([84, 2]).
