âœ“ WandB initialized in Online mode
Traceback (most recent call last):
  File "/home/ajinkya/projects/TestRepo_MsThesis_Ajinkya/week9/main.py", line 266, in <module>
    main()
  File "/home/ajinkya/projects/TestRepo_MsThesis_Ajinkya/week9/main.py", line 247, in main
    illusion_testing(trainloader,validationloader,config,20)
  File "/home/ajinkya/projects/TestRepo_MsThesis_Ajinkya/week9/main.py", line 226, in illusion_testing
    net.load_state_dict(torch.load(f'{config.load_model_path}/{config.model_name}_{iteration_index}.pth',map_location=config.device,weights_only=True))
  File "/home/ajinkya/miniconda3/envs/cuda_pyt/lib/python3.12/site-packages/torch/nn/modules/module.py", line 2584, in load_state_dict
    raise RuntimeError(
RuntimeError: Error(s) in loading state_dict for Net:
	Missing key(s) in state_dict: "conv1.weight", "conv1.bias", "conv2.weight", "conv2.bias", "conv3.weight", "conv3.bias", "conv4.weight", "conv4.bias", "fc1.weight", "fc1.bias", "fc2.weight", "fc2.bias", "fc3.weight", "fc3.bias", "fc3_fb.weight", "fc3_fb.bias", "fc2_fb.weight", "fc2_fb.bias", "fc1_fb.weight", "fc1_fb.bias", "deconv4_fb.weight", "deconv4_fb.bias", "deconv3_fb.weight", "deconv3_fb.bias", "deconv2_fb.weight", "deconv2_fb.bias", "deconv1_fb.weight", "deconv1_fb.bias".
	Unexpected key(s) in state_dict: "conv1", "conv2", "conv3", "conv4", "deconv1_fb", "deconv2_fb", "deconv3_fb", "deconv4_fb".
