âœ“ WandB initialized in Online mode
The Iteration0:
================================
Epoch:0 and AverageLoss:0.6927863857414149 and Reconstruction Loss:0.0025976919569075108
Epoch:1 and AverageLoss:0.6919771070721783 and Reconstruction Loss:0.0024636348243802786
Epoch:2 and AverageLoss:0.6911970927745481 and Reconstruction Loss:0.002079104771837592
Epoch:3 and AverageLoss:0.6899840077267417 and Reconstruction Loss:0.002872433280572295
Epoch:4 and AverageLoss:0.688162771961357 and Reconstruction Loss:0.002830750308930874
Epoch:5 and AverageLoss:0.6856998748417142 and Reconstruction Loss:0.0022669199388474226
Epoch:6 and AverageLoss:0.6819218615942364 and Reconstruction Loss:0.002470607403665781
Epoch:7 and AverageLoss:0.6767591268201417 and Reconstruction Loss:0.003220346523448825
Epoch:8 and AverageLoss:0.6695698665667184 and Reconstruction Loss:0.002546821953728795
Epoch:9 and AverageLoss:0.6601062069965314 and Reconstruction Loss:0.002699062693864107
Model Saved Sucessfully
The Iteration1:
================================
Epoch:0 and AverageLoss:0.6505100327202037 and Reconstruction Loss:0.0029578376561403275
Epoch:1 and AverageLoss:0.6419183506241327 and Reconstruction Loss:0.0028655417263507843
Epoch:2 and AverageLoss:0.6324953157690507 and Reconstruction Loss:0.0023466963320970535
Epoch:3 and AverageLoss:0.6217164714125138 and Reconstruction Loss:0.0025425245985388756
Epoch:4 and AverageLoss:0.6100612916523898 and Reconstruction Loss:0.002602869411930442
Traceback (most recent call last):
  File "/home/ajinkya/projects/TestRepo_MsThesis_Ajinkya/week9/main.py", line 243, in <module>
    main()
  File "/home/ajinkya/projects/TestRepo_MsThesis_Ajinkya/week9/main.py", line 226, in main
    decide_training_model(config.training_condition, save_dir, trainloader, testloader, config,iteration_index)
  File "/home/ajinkya/projects/TestRepo_MsThesis_Ajinkya/week9/main.py", line 208, in decide_training_model
    result=cond_to_func[condition]()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ajinkya/projects/TestRepo_MsThesis_Ajinkya/week9/main.py", line 205, in <lambda>
    "illusion_train": lambda:fine_tuning_using_illusions(save_dir, trainloader, testloader,config,iteration_index),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ajinkya/projects/TestRepo_MsThesis_Ajinkya/week9/main.py", line 189, in fine_tuning_using_illusions
    train_bool=illusion_pc_training(net,trainloader,testloader,"fine_tuning",config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ajinkya/projects/TestRepo_MsThesis_Ajinkya/week9/illusion_pc_train.py", line 29, in illusion_pc_training
    for images,labels,_ in trainloader:
                           ^^^^^^^^^^^
  File "/home/ajinkya/miniconda3/envs/cuda_pyt/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 701, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/home/ajinkya/miniconda3/envs/cuda_pyt/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 757, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ajinkya/miniconda3/envs/cuda_pyt/lib/python3.12/site-packages/torch/utils/data/_utils/fetch.py", line 50, in fetch
    data = self.dataset.__getitems__(possibly_batched_index)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ajinkya/miniconda3/envs/cuda_pyt/lib/python3.12/site-packages/torch/utils/data/dataset.py", line 420, in __getitems__
    return [self.dataset[self.indices[idx]] for idx in indices]
            ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/home/ajinkya/projects/TestRepo_MsThesis_Ajinkya/week9/customdataset.py", line 25, in __getitem__
    image = Image.open(img_name).convert("RGB")
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/ajinkya/miniconda3/envs/cuda_pyt/lib/python3.12/site-packages/PIL/Image.py", line 3511, in open
    im = _open_core(fp, filename, prefix, formats)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ajinkya/miniconda3/envs/cuda_pyt/lib/python3.12/site-packages/PIL/Image.py", line 3499, in _open_core
    im = factory(fp, filename)
         ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ajinkya/miniconda3/envs/cuda_pyt/lib/python3.12/site-packages/PIL/ImageFile.py", line 144, in __init__
    self._open()
  File "/home/ajinkya/miniconda3/envs/cuda_pyt/lib/python3.12/site-packages/PIL/PngImagePlugin.py", line 771, in _open
    cid, pos, length = self.png.read()
                       ^^^^^^^^^^^^^^^
  File "/home/ajinkya/miniconda3/envs/cuda_pyt/lib/python3.12/site-packages/PIL/PngImagePlugin.py", line 175, in read
    if not is_cid(cid):
           ^^^^^^^^^^^
KeyboardInterrupt
Exception ignored in atexit callback: <function _start_and_connect_service.<locals>.teardown_atexit at 0x7f6bb0e19760>
Traceback (most recent call last):
  File "/home/ajinkya/miniconda3/envs/cuda_pyt/lib/python3.12/site-packages/wandb/sdk/lib/service/service_connection.py", line 54, in teardown_atexit
    conn.teardown(hooks.exit_code)
  File "/home/ajinkya/miniconda3/envs/cuda_pyt/lib/python3.12/site-packages/wandb/sdk/lib/service/service_connection.py", line 182, in teardown
    self._router.join()
  File "/home/ajinkya/miniconda3/envs/cuda_pyt/lib/python3.12/site-packages/wandb/sdk/interface/router.py", line 75, in join
    self._thread.join()
  File "/home/ajinkya/miniconda3/envs/cuda_pyt/lib/python3.12/threading.py", line 1149, in join
    self._wait_for_tstate_lock()
  File "/home/ajinkya/miniconda3/envs/cuda_pyt/lib/python3.12/threading.py", line 1169, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt:
